name1 =(input("Nhập tên người thứ nhất:"))
t1 =int(input("Điểm toán:"))
l1 =int(input("ĐIểm lý:"))
h1 = int(input("Điểm hóa:"))
print("Tên sinh viên:",name1,"- Điểm TB:", round((t1+l1+h1)/3, 2))
name2 =(input("Nhập tên người thứ hai:"))
t2 =int(input("Điểm toán:"))
l2 =int(input("ĐIểm lý:"))
h2 = int(input("Điểm hóa:"))
print("Tên sinh viên:",name2,"- Điểm TB:", round((t2+l2+h2)/3, 2))
name3=(input("Nhập tên người thứ ba:"))
t3 =int(input("Điểm toán:"))
l3 =int(input("ĐIểm lý:"))
h3 = int(input("Điểm hóa:"))
print("Tên sinh viên:",name3,"- Điểm TB:", round((t3+l3+h3)/3, 2))

